### ISSUE TITLE
hi bro. do you have any script for windows 10 using facebook brute force method :)

### ISSUE THREAD

**Issue by glerinsonum** [joridos/custom-ssh-backdoor#1]
hi bro. do you have any script for windows 10 using facebook brute force method :)

**Comment by joridos** [comment]
Hi, not for now, i'm planing to create one.

**Comment by glerinsonum** [comment]
ok @joridos

**Comment by glerinsonum** [comment]
@joridos https://github.com/jfilipe/facebook-hack

**Comment by joridos** [comment]
Hello @glerinsonum, it's very simple, the printscreen on the README is showing the backdoor listen on the left side, and in the right side the VM running windows simulating a remote host, just need to run the server.py first, and then the client.
